[US] As an Organization Admin I want to be able to track important changes to the Entries
KoalicjaOtwartyKrakow/kokon pull request #5
Opened 2022-04-09 17:07 UTC by unjello

For audit and transparency into the process purposes, the system cannot just overwrite some of the data. Organization Admins need to be able to see the history of Guest assignments to Accommodation Units or which Team Member worked on which Guest Entry.

2022-04-11 02:44 UTC, salamlab-service-account requested changes

2022-04-11 02:44 UTC, salamlab-service-account commented on requirements/0003-audit-trail.md
> +A new table SHALL be created, tracking at least:
The reality of `SQLAlchemy-Continuum` is as follows:
* there is a `transaction` table with columns `issued_at` and `id`
* for actual versions data we have a table per entity type, not one common table
* each versions table has the same schema as the normal entities table + following additional columns:
  * `transaction_id`, fk to the `transaction` table
  * `end_transaction_id`, the id of the next transaction that touched the same row, `null` if the current row is the latest version
  * `operation_type` – CREATE / UPDATE / DELETE, coded in a `smallint`
* values in the row are from *after* the change (not sure how it works for deletes tho)
* ^ this means that there is no need to extend continuum to track, e.g., who made the change. Instead, we can just add a `updated_by` column to each app table, and then we'll get the data we need.

2022-04-11 02:44 UTC, salamlab-service-account commented on requirements/0003-audit-trail.md
> +A new table SHALL be created, tracking at least:
This is probably too detailed for an RFC, I just wanted to sell you all the current context to decide how/if to adjust the RFC

2022-04-11 02:44 UTC, salamlab-service-account commented on requirements/0003-audit-trail.md
> +No impact.
We'll need `iac` to define credentials for the non-superadmin app user that will be created by migrations (migrations will run using the current superadmin). `iac` will not be responsible for creating the account, only the coordination of creds between migrations and app.

We'll also need to stop providing the superadmin creds to the app and rotate those creds.

2022-04-11 02:44 UTC, salamlab-service-account commented on requirements/0003-audit-trail.md
> +Endpoints SHALL track changes to Guest entity - including at least field `guest.claimed_by` and `guest.accommodation_unit_id`.
Right now we track versions of accommodation units and guests. IMO we could track hosts versions as well. The audit log is useful not only for investigating what changes were made in some specific case, but also for generating reports.

Sometimes specific types of records might require us to slightly alter how the version tracking works, but this is out of scope of this RFC.

2022-04-11 02:45 UTC, salamlab-service-account commented
Whooops I forgot to change the account, these comments are from @mlazowik

2022-04-11 02:46 UTC, mlazowik commented
^ I confirm that :P

2022-04-14 19:32 UTC, mlazowik commented on requirements/0003-audit-trail.md
> +A non-superadmin user SHALL be created to be used by app. Credentials rotation SHALL be implemented for this newly created user.
Hm, how do we expect the rotation to work? Recurring task?

Also what is the motivation for rotation? You can't even connect to the database without going through Google auth backend by 2FA, we do not have any service account keys anywhere. The only way for someone who is not in the `infra-root@`group to get into the db they would have to hack our backend code, but then they can just read the password from env.

2023-03-22 18:22 UTC, closed without merging